enjektor/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap

from pages.sitemaps import StaticViewSitemap


sitemaps = {
	'services' : StaticViewSitemap,
}


urlpatterns = [
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('_nested_admin/', include('nested_admin.urls')),
    path('robots.txt/', TemplateView.as_view(template_name="robots.txt", content_type ="text/plain")),
    path('sitemap.xml/', sitemap, {'sitemaps':sitemaps}),
]
if settings.DEBUG: 
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views


app_name = 'pages'
urlpatterns = [
    path('', views.index, name='home'),
    path('iletisim/', views.contact, name='contact'),
    path('hakkimizda/', views.about, name='about'),
    path('hizmetlerimiz/', views.services, name='services'),
    path('urunlerimiz/', views.products, name='products'),
]

templates/include/footer.html
{% load static %}


<footer id="footer" class="dark bg-color border-top-0">
    <div class="container">

        <!-- Footer Widgets
        ============================================= -->
        <div class="footer-widgets-wrap">

            <div class="row justify-content-center">
                <!-- <div class="col-md-7 mb-3 text-center">
                    <h3 class="display-3 font-weight-normal font-display mb-5 text-white">Download Our COVID Care App.</h3>
                    <a href="#" class="button button-light button-large rounded-pill bg-color-2 text-dark px-4 py-2 h-op-09 op-ts">Register</a>
                    <a href="#" class="button button-light button-large bg-white rounded-pill color px-4 py-2 ml-2 h-op-09 op-ts">Download App</a>
                </div>
                <div class="w-100 clear line"></div> -->
                <div class="col-lg-9">
                    <div class="widget clearfix">
                        <div class="row col-mb-30">
                            <div class="col-lg-3 col-6 widget_links">
                                <ul>
                                    <li><a href="{% url 'pages:home' %}">AnaSayfa</a></li>
                                    <li><a href="{% url 'pages:about' %}">Hakkımızda</a></li>
                                    <li><a href="{% url 'pages:services' %}">Hizmetlerimiz</a></li>
                                    <li><a href="{% url 'pages:products' %}">Ürünlerimiz</a></li>
                                    <li><a href="{% url 'pages:contact' %}">İletişim</a></li>
                                </ul>
                            </div>

                            <!-- <div class="col-lg-3 col-6 widget_links">
                                <ul>
                                    <li><a href="#">Shop</a></li>
                                    <li><a href="#">Portfolio</a></li>
                                    <li><a href="#">Blog</a></li>
                                    <li><a href="#">Events</a></li>
                                    <li><a href="#">Forums</a></li>
                                </ul>
                            </div> -->

                            <!-- <div class="col-lg-3 col-6 widget_links">
                                <ul>
                                    <li><a href="#">Corporate</a></li>
                                    <li><a href="#">Agency</a></li>
                                    <li><a href="#">eCommerce</a></li>
                                    <li><a href="#">Personal</a></li>
                                    <li><a href="#">One Page</a></li>
                                </ul>
                            </div> -->

                            <!-- <div class="col-lg-3 col-6 widget_links">
                                <ul>
                                    <li><a href="#">Corporate</a></li>
                                    <li><a href="#">Agency</a></li>
                                    <li><a href="#">eCommerce</a></li>
                                    <li><a href="#">Personal</a></li>
                                    <li><a href="#">One Page</a></li>
                                </ul>
                            </div> -->
                        </div>

                    </div>
                </div>

                <div class="col-lg-3 mt-5 mt-lg-0 text-center text-lg-right">
                    <div class="widget clearfix">

                        <div class="row">
                            <div class="col-12 mb-3">
                                <h3>Bizi Arayın:</h3>
                                <!-- <h4 class="h4">{{setting.phone}}</h4> -->
                                <h4 class="h4">{{setting.phone}}</h4>
                            </div>

                            <div class="col-12 d-flex justify-content-center justify-content-lg-end">
                                <a href="https://api.whatsapp.com/send?phone={{setting.whatsapp_phone}}" class="social-icon si-colored si-whatsapp" title="WhatsApp">
                                    <i class="icon-whatsapp"></i>
                                    <i class="icon-whatsapp"></i>
                                  </a>
                                    <a href="{{setting.facebook_url}}" class="social-icon  si-colored si-facebook"><i class="icon-facebook"></i></a>
                                    <a href="{{setting.instagram_url}}" class="social-icon  si-colored si-instagram"><i class="icon-instagram"></i></a>
                                    <a href="{{setting.linkedin_url}}" class="social-icon  si-colored si-linkedin"><i class="icon-linkedin"></i></a>
                                    <a href="{{setting.twitter_url}}" class="social-icon  si-colored si-twitter"><i class="icon-twitter"></i></a>

                            </div>

                            <div class="col-12 mt-5 text-white-50 ">
                                All Rights Reserved <br>&copy; 2021 by RasyonelDental<br>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

        </div><!-- .footer-widgets-wrap end -->
    </div>
</footer><!-- #footer end -->

templates/include/kart.html
<div class="row counters clearfix mb-0 topmargin-sm align-items-stretch">
    {% for extra in extras %}
    {% if extra.ekstra_tipi.title == 'kart' %}
    {% for extracontent in extra.ekstracontent_set.all %}
    <div class="col-xs-12 col-sm dark text-center min-vh-40" style="background: url('{{extracontent.image.url}}') no-repeat center center; background-size: cover;">
        <div class="bg-overlay">
            <div class="bg-overlay-content dark">
                <div>
                    <i class="{{extracontent.icon.title}}"></i>
                    <div class="counter counter-lined"><span data-from="0" data-to="{{extracontent.short_content}}" data-refresh-interval="10" data-speed="2300"></span></div>
                    <h5>{{extracontent.title}}</h5>
                </div>
            </div>
            <div class="bg-overlay-bg op-ts op-1" data-hover-animate="op-0" data-hover-animate-out="op-1" style="background-color: rgba(229, 57, 53, 0.8);"></div>
        </div>
    </div>
    {% endfor %}
    {% endif %}
    {% endfor %}


</div>

templates/include/messages.html
{% if messages %}
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  {{ message }}
</div>
{% endfor %}

{%endif %}

templates/include/navbar.html
{% load static %}
{% url 'pages:home' as home_url%}
{% url 'pages:about' as about_url%}
{% url 'pages:products' as product_url%}
{% url 'pages:contact' as contact_url%}
{% url 'pages:services' as service_url%}
<!-- <div id="wrapper" class="clearfix">	 -->
		<!-- Top Bar
		============================================= -->
		<div id="top-bar" class="py-4 text-center bg-color-2">
			<div class="container clearfix">
				<!-- <h4 class="mb-0 h6 font-normal">COVID-19? We're in this together &amp; will get through this, Together. <a href="#" class="color font-weight-bold border-bottom border-width-2 border-color font-secondary ml-2">Learn more</a><i class="icon-chevron-right icon-stacked text-smaller color"></i></h4> -->
				<h1 class="mb-0 h6 font-normal">{{setting.navmessage}} <a href="{% url 'pages:services' %}" class="color font-weight-bold border-bottom border-width-2 border-color font-secondary ml-2">Detalı Bigi için</a><i class="icon-chevron-right icon-stacked text-smaller color"></i></h1>
			</div>
		</div><!-- #top-bar end -->

		<!-- Header
		============================================= -->
		<header id="header" class="">
			<div id="header-wrap">
				<div class="container">
					<div class="header-row">

						<!-- Logo
						============================================= -->
						<div id="logo">
							<a href="{% url 'pages:home' %}" class="standard-logo"><img src="{{setting.logo1.url}}" alt="Canvas Logo"></a>
							<a href="{% url 'pages:home' %}" class="retina-logo"><img src="{{setting.logo2.url}}" alt="Canvas Logo"></a>
						</div><!-- #logo end -->

						<!-- Primary Menu Mobile Trigger
						============================================= -->
						<div id="primary-menu-trigger">
							<svg class="svg-trigger" viewBox="0 0 100 100"><path d="m 30,33 h 40 c 3.722839,0 7.5,3.126468 7.5,8.578427 0,5.451959 -2.727029,8.421573 -7.5,8.421573 h -20"></path><path d="m 30,50 h 40"></path><path d="m 70,67 h -40 c 0,0 -7.5,-0.802118 -7.5,-8.365747 0,-7.563629 7.5,-8.634253 7.5,-8.634253 h 20"></path></svg>
						</div>

						<!-- Header Buttons
						============================================= -->
						<!-- <div class="header-misc">
							<a href="#" class="button rounded-pill bg-color-2 button-light text-dark ls0 font-weight-medium m-0">Register</a>
							<a href="#" class="button rounded-pill ls0 font-weight-medium my-0 ml-2 d-none d-sm-flex">Download App</a>
						</div> -->

						<!-- Primary Navigation
						============================================= -->
						<nav class="primary-menu">

							<ul class="menu-container">
								<li class="menu-item {% if request.get_full_path  == home_url %}current{% endif %}">
									<a class="menu-link active" href="{% url 'pages:home' %}">AnaSayfa</a>
								</li>
								
	
								<li class="menu-item {% if request.get_full_path  == about_url %}current{% endif %}"><a class= "menu-link" href="{% url 'pages:about' %}">Hakkımızda</a>
								

								<li class="menu-item {% if request.get_full_path  == service_url %}current{% endif %}"><a class="menu-link" href="{% url 'pages:services' %}"><div>Hizmetlerimiz</div></a></li>
								<li class="menu-item {% if request.get_full_path  == product_url %}current{% endif %}"><a class="menu-link" href="{% url 'pages:products' %}"><div>Ürünlerimiz</div></a></li>
								<li class="menu-item {% if request.get_full_path  == contact_url %}current{% endif %}"><a class="menu-link" href="{% url 'pages:contact' %}"><div>İletişim</div></a></li>
							</ul>





							<!-- <ul class="menu-container">
								{% for header in headers %}
				  
								<li
								  class="menu-item {% if forloop.counter == 1 %}current{% endif%}"
								>
								  <a
									class="menu-link"
									href="{% if forloop.counter == 1 %}{% url 'pages:home' %}{% else %}{% url 'pages:header-detail' header.slug %}{% endif%}"
									><div>{{header.title}}</div></a
								  >
								  {% if header.is_dropdown %}
								  <ul class="sub-menu-container">
									<li class="menu-item">
									  <a class="menu-link" href="demo-medical-doctors-lists.html"
										><div>2 columns - List style</div></a
									  >
									</li>
									<li class="menu-item">
									  <a class="menu-link" href="demo-medical-doctors-3.html"
										><div>3 columns</div></a
									  >
									</li>
									<li class="menu-item">
									  <a class="menu-link" href="demo-medical-doctors.html"
										><div>4 columns</div></a
									  >
									</li>
								  </ul>
								  {% endif %}
								</li>
								{% endfor %}
							  </ul> -->

						</nav><!-- #primary-menu end -->

					</div>
				</div>
			</div>
			<div class="header-wrap-clone"></div>
		</header><!-- #header end -->