enjektor/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap

from pages.sitemaps import StaticViewSitemap


sitemaps = {
	'services' : StaticViewSitemap,
}


urlpatterns = [
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('_nested_admin/', include('nested_admin.urls')),
    path('robots.txt/', TemplateView.as_view(template_name="robots.txt", content_type ="text/plain")),
    path('sitemap.xml/', sitemap, {'sitemaps':sitemaps}),
]
if settings.DEBUG: 
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views


app_name = 'pages'
urlpatterns = [
    path('', views.index, name='home'),
    path('iletisim/', views.contact, name='contact'),
    path('hakkimizda/', views.about, name='about'),
    path('hizmetlerimiz/', views.services, name='services'),
    path('urunlerimiz/', views.products, name='products'),
]

pages/models.py
from django.db import models
from django.utils.text import slugify
from ckeditor.fields import RichTextField

class Home(models.Model):
    title = models.CharField("Başlık", max_length = 75)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name= "Created At")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated At")
    herocontent= models.CharField("Slayt içindeki yazı", max_length=150)
    subherocontent=models.CharField("Slayt içindeki alt yazı", blank=True, max_length=150)
    image = models.ImageField("resim", null = True, blank = True)
    pagemaintitle= models.CharField("Ana sayfa ana başlığı", max_length=150)
    pagesubcontent=models.CharField("Ana sayfa alt içerik", blank=True, max_length=150)
    below_title=models.CharField("Alt Başlık", blank=True, max_length=150)
    below_image = models.ImageField("Alt Resim", null = True, blank = True)
    below_content=models.CharField("Alt içerik", blank=True, max_length=200)
    last_title=models.CharField("En Alt Başlık", blank=True, max_length=75)
    last_image1= models.ImageField("En Alt Resim", null = True, blank = True)
    last_image2= models.ImageField("En Alt Resim", null = True, blank = True)
    last_content=models.CharField("En Alt içerik", blank=True, max_length=200) 
      
    description = models.CharField("Sayfanın search engine açıklaması", max_length = 120)
    is_navbar = models.BooleanField("Navbarda gösterilsin mi?", default = True)
    active = models.BooleanField("Sitede gösterilsin mi?", default = True)
    order = models.SmallIntegerField("Sıralama", default = 0)
    is_dropdown = models.BooleanField("Alt başlıkları olsun mu", default = False)
    # template = models.ForeignKey("pages.Template", on_delete = models.SET_NULL, null = True, blank = True)
    # ekstras = models.ManyToManyField("pages.Ekstra", null = True, blank = True)
    
    class Meta:
        ordering = ['order']
        verbose_name_plural = "AnaSayfa Ana İçerik "
        verbose_name ="AnaSayfa Ana İçerikler "
    
    
    def __str__(self):
        return self.title
    
    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.title.replace("ı", "i").replace("I", "i").lower())
    #     super(Header, self).save(*args, **kwargs)

class HomeDetail(models.Model):
    title = models.CharField("Başlık", max_length = 75)
    content = RichTextField("İçerik")
    image = models.ImageField("resim", null = True, blank = True)
    order = models.SmallIntegerField("Sıralama", default = 0)
    active = models.BooleanField("Sitede gösterilsin mi?", default = True)
    
    class Meta:
        ordering = ['order']
        verbose_name_plural = "Anasayfa Şerit İçerikler"
        verbose_name ="Anasayfa Şerit İçerik"
        
    def __str__(self): 
        return self.title

class HomeMiddleHeader(models.Model):
    title=models.CharField(" Başlık", blank=True, max_length=150)
    image = models.ImageField(" Resim", null = True, blank = True)
    image_def= models.CharField("Resim Açıklaması", blank = True, max_length=50)
    content=models.CharField(" Başlık içerik", blank=True, max_length=250)
    order = models.SmallIntegerField("Sıralama", default = 0)
    active = models.BooleanField("Sitede gösterilsin mi?", default = True)
    
    class Meta:
        ordering = ['order']
        verbose_name_plural = "Ana Sayfa ikinci  Alan İçerikler"
        verbose_name ="Ana Sayfa ikinci Alan İçerik"
        
    def __str__(self): 
        return self.title
    
class HomeMiddleDetail(models.Model):
    header = models.ForeignKey(HomeMiddleHeader, null= True, blank = True, on_delete = models.CASCADE)
    title = models.CharField("Başlık", max_length = 75)
    content = RichTextField("İçerik")
    order = models.SmallIntegerField("Sıralama", default = 0)
    # icon = models.ForeignKey("pages.Icon", null= True, blank = True, on_delete = models.CASCADE)
    active = models.BooleanField("Sitede gösterilsin mi?", default = True)
    
    
    class Meta:
        ordering = ['order']
        verbose_name_plural = "Ana Sayfa Orta Alan Detaylar"
        verbose_name ="Ana Sayfa Orta Alan Detay" 
        
    def __str__(self): 
        return self.title
        
# class HomeIcon(models.Model):
#     title = models.CharField("Başlık", max_length = 75)
#     order = models.SmallIntegerField("Sıralama", default = 0)
#     icon = models.ForeignKey("pages.Icon", null= True, blank = True, on_delete = models.CASCADE)
#     active = models.BooleanField("Sitede gösterilsin mi?", default = True)
    
    
#     class Meta:
#         ordering = ['order']
#         verbose_name_plural = "Anasayfa Alt İconlar"
#         verbose_name ="Anasayfa Alt İcon" 
        
#     def __str__(self): 
#         return self.title
   
class HomeFooterUp(models.Model):
    title = models.CharField("Başlık", max_length = 75)
    order = models.SmallIntegerField("Sıralama", default = 0)
    active = models.BooleanField("Sitede gösterilsin mi?", default = True)
    content1 = models.CharField("İçerik1", max_length = 75, blank=True)
    content2 = models.CharField("İçerik2", max_length = 75, blank=True)
    content3 = models.CharField("İçerik3", max_length = 75, blank=True)
    content4 = models.CharField("İçerik4", max_length = 75, blank=True)
    content5 = models.CharField("İçerik5", max_length = 75, blank=True)
    content6 = models.CharField("İçerik6", max_length = 75, blank=True)
    rightcontent=models.CharField("Sağiçerik", max_length = 75, blank=True)
    
    
    class Meta:
        ordering = ['order']
        verbose_name_plural = "Anasayfa Footer Üstü Kartlar"
        verbose_name ="Anasayfa Footer Üstü Kart"  
        
    def __str__(self): 
        return self.title    

# class Icon (models.Model):
#     title = models.CharField("İcon adı", max_length = 75)
    
#     def __str__(self):
#         return self.title        
        
             
class ContactInfo(models.Model):
    name = models.CharField("İSİM:", max_length = 30)
    email = models.EmailField("Eposta adresi:")
    # number = models.SmallIntegerField("Telefon Numaranız:")
    message = models.TextField("Mesajınız:")
    # active = models.BooleanField("Sitede gösterilsin mi?", default = True)
    # publish_date=models.DateTimeField("Yayınlanma Tarihi", auto_now_add=True)

    class Meta:
        verbose_name = 'Gelen Mesaj'
        verbose_name_plural = 'Gelen Mesajlar'

    def __str__(self):
        return self.name   

class About(models.Model):
    about_title= models.CharField("Hakkımızda Resim Ortası Başlık", max_length=50)
    about_main_image= models.ImageField("Hakkımızda Ana Resim", null = True, blank = True)
    description = models.CharField("Google'da çıkacak olan yazı", max_length=150)
    keywords = models.CharField("Google'da çıkması için gerekli anahtar kelimeler", max_length=150)
    images_title= models.CharField("Hakkımızda Resimler Başlık", max_length=50)
    images_content= models.TextField("Hakkımızda Resimler İçerik", max_length=50)
    youtube_url = models.URLField("Hakkımızda Video Linki")
    button_name= models.CharField("Hakkımızda Video Buton Üzerindeki Yazı", max_length=50)
    images_image1= models.ImageField("Hakkımızda Resimler Resim1", null = True, blank = True)
    images_image1_content= models.CharField("Hakkımızda Resimler Resim1 açıklaması", max_length=50)
    images_image2= models.ImageField("Hakkımızda Resimler Resim2", null = True, blank = True)
    images_image2_content= models.CharField("Hakkımızda Resimler Resim2 açıklaması", max_length=50)
    images_image3= models.ImageField("Hakkımızda Resimler Resim3", null = True, blank = True)
    images_image3_content= models.CharField("Hakkımızda Resimler Resim3 açıklaması", max_length=50)
    images_image4= models.ImageField("Hakkımızda Resimler Resim4", null = True, blank = True)
    images_image4_content= models.CharField("Hakkımızda Resimler Resim4 açıklaması", max_length=50)
    middle_title=models.CharField("Hakkımızda Footer Üstü Başlık", blank = True, max_length=50)
    middle_content=models.CharField("Hakkımızda Footer Üstü İçerik", blank = True, max_length=100)
    middle_image1= models.ImageField("Hakkımızda Footer Üstü Resim",blank = True)
    middle_image1_content= models.CharField("Hakkımızda Footer Üstü Resim Açıklaması",blank = True, max_length=50)
    middle_image2= models.ImageField("Hakkımızda Footer Üstü Resim", blank = True)
    middle_image2_content= models.CharField("Hakkımızda Footer Üstü Resim Açıklaması", blank = True, max_length=50)
    
    
    
    class Meta:
        verbose_name = 'Hakkımızda İçerik'
        verbose_name_plural = 'Hakkımızda İçerikler'

    def __str__(self):
        return self.about_title 
    
    
class AboutContent(models.Model):
    about = models.ForeignKey(About, on_delete = models.CASCADE, related_name='aboutcontent')
    title= models.CharField("Hakkımızda Başlık", max_length=50)
    image= models.ImageField("Hakkımızda Resim", null = True, blank = True)
    content=RichTextField(" Hakkımızda içerik", blank=True, max_length=250)
    
    class Meta:
        verbose_name = 'Hakkımızda Bilgi'
        verbose_name_plural = 'Hakkımızda Bilgiler'

    def __str__(self):
        return self.title 
    
class Services(models.Model):
    title= models.CharField("Ana Başlık", max_length=50)
    description = models.CharField("Google'da çıkacak olan yazı", max_length=150)
    keywords = models.CharField("Google'da aramalarda çıkabilmek için gerekli anahtar kelimler", max_length=150)   
    main_image= models.ImageField("Ana Resim", null = True, blank = True)
    card1_title= models.CharField("Hizmetler Başlık", max_length=50)
    card1_content= RichTextField("Hizmetler Açıklama")
    card1_image= models.ImageField("Hizmetler Resim", null = True, blank = True)
    card1_image_cont= models.CharField("Hizmetler Resim Açıklaması", max_length=50)
    card2_title= models.CharField("Hizmetler Başlık", max_length=50)

templates/about.html
{% extends 'layout.html' %} 
{% load static %} {% load crispy_forms_tags %}

{% block title %} <title>Rasyonel Dental-Hakkımızda</title>{% endblock %}}

{% block metalar %}
<meta content="{{products.description}}" name="description">
<meta content="{{about.keywords}}" name="keywords">
{% endblock %}
{% block content %}

		<!-- Page Title
		============================================= -->


		<!-- Content
		============================================= -->
		<div id="slider" class="slider-element dark py-0" style="background-size: cover; background-image: url('{{about.about_main_image.url}}'); background-position: center center; background-repeat: no-repeat;">

			<div class="container">
				<div class="row text-center py-5 min-vh-md-75 justify-content-center align-items-center">
					<div class="col-lg-6">
						<h5 class="mb-1 text-uppercase ls3 text-white-50 font-body" >Hakkımızda</h5>
						<h2 class="display-3 font-weight-bolder ls3 font-display mb-5" style="color: #1ABC9C">{{about.about_title}}</h2>
					</div>
				</div>
			</div>
		</div>

		<!-- Content
		============================================= -->
		<section id="content">
			<div class="content-wrap pb-0">

				<div class="container py-5">

					<!-- Tab
					============================================= -->
					<div class="row justify-content-between">
						<div class="col-lg-4 col-md-5 mb-5 mb-md-0">
							<div class="nav flex-column nav-pills" id="canvas-tabs-tab" role="tablist" aria-orientation="vertical">
								
								{% for about in aboutcontents %}
									
									
								<a class="nav-link {% if forloop.counter == 1 %}active{% endif %}" id="canvas-tabs-{{forloop.counter}}-tab" data-toggle="pill" href="#canvas-tabs-{{forloop.counter}}" role="tab" >
									<h3><span class="color-2 font-body mr-1">{{forloop.counter}}.</span> {{about.title}}</h3>
									<p>{{about.content|safe}}</p>
								</a>
								
								{% endfor %}

								
								<a href="{{about.youtube_url}}" class="button button-large rounded-pill bg-color-2 button-light text-dark text-center ls0 font-weight-medium ml-0 mt-3 w-auto" data-lightbox="iframe"><i class="icon-play-circle mr-1" style="position: relative; top: 1px; margin-right: 5px;"></i> {{about.button_name}}</a>
							</div>
						</div>

						<div class="col-md-7">
							<div class="tab-content" id="canvas-tabContent">

								{% for about in aboutcontents %}
									
								
								<div class="tab-pane show {% if forloop.counter == 1 %}active{% endif %} text-center" id="canvas-tabs-{{forloop.counter}}" role="tabpanel" aria-labelledby="canvas-tabs-{{forloop.counter}}-tab">
									<img src="{{about.image.url}}" alt="Image" height="350">
									<div class="clear"></div>
									<div class="d-block text-left mt-5 mw-xs">
										<h3 class="mb-3">{{about.title}}</h3>
										<p class="mb-0">{{about.content|safe}}</p>
									</div>
								</div>
								{% endfor %}
							</div>
						</div>
					</div>

				</div>

				<!-- Clients Gallery
				============================================= -->
				<div class="section" style="background-color: rgba(15,100,88,.15); padding: 80px 0">
					<div class="container">
						<div class="mw-md mx-auto">
							<div class="row align-items-end mb-1">
								<div class="col-md-3 col-6">
									<img src="{{about.images_image1.url}}" alt="{{about.images_image1_content}}" class="border border-width-3 border-light">
								</div>
								<div class="col-md-4 col-6">
									<img src="{{about.images_image2.url}}" alt="{{about.images_image2_content}}" class="border border-width-3 border-light">
								</div>
								<div class="col-md-5 my-4 my-md-0">
									<h3 class="mb-3 color h1">{{about.images_title}}</h3>
									<p class="mb-0">{{about.images_content}}</p>
								</div>
							</div>
							<div class="clear"></div>
							<div class="row mt-4">
								<div class="col-md-6 col-6">
									<img src="{{about.images_image3.url}}" alt="{{about.images_image3_content}}" class="border border-width-3 border-light">
								</div>
								<div class="col-md-6 col-6">
									<img src="{{about.images_image4.url}}" alt="{{about.images_image4_content}}" class="border border-width-3 border-light">
								</div>
							</div>
						</div>
					</div>
				</div>

				<!-- Download App Section
				============================================= -->
				<div class="section py-md-0 section-mobile bg-color-2" style="background:no-repeat center left / contain;">
					<div class="container">
						<div class="row align-items-center justify-content-between">

							<div class="col-lg-5 col-md-6 py-5 py-lg-0">
								<h3 class="display-3 color font-weight-normal font-display mb-5">{{about.middle_title}}</h3>
								<p class="text-large color">{{about.middle_content}}</p>
								<!-- <div>
									<a href="#"><img src="demos/articles/images/appstore.png" alt="Image" height="54" class="mt-3"></a>
									<a href="#"><img src="demos/articles/images/googleplay.png" alt="Image"  class="ml-xl-3 ml-lg-1 mt-3 ml-0 " height="54"></a>
								</div> -->
							</div>

							<div class="col-lg-6 col-md-6 mt-5 mt-sm-0">
								<div class="d-none d-lg-flex">
									<img src="{{about.middle_image1.url}}" class="fast" alt="{{about.middle_image1_content}}" style="height: 350px;margin: 1rem;border-radius: 1rem;" data-animate="fadeInUp" data-delay="200">
									<img src="{{about.middle_image2.url}}" class="fast" alt="{{about.middle_image2_content}}" style="height: 350px;margin: 1rem;border-radius: 1rem;" data-animate="fadeInUp">
								</div>
								<!-- <img src="demos/covid-care/images/iphone.png" alt="Image" class="d-block d-lg-none px-5 px-sm-0 p-md-5"> -->
							</div>

						</div>
					</div>
				</div>

			</div>
		</section><!-- #content end -->



	<!-- Go To Top
	============================================= -->
	<!-- <div id="gotoTop" class="icon-angle-up"></div> -->


{% endblock content %}

templates/index.html
{% extends 'layout.html' %} 
{% load static %} {% load crispy_forms_tags %}


    

{% block content %}



	<!-- Document Wrapper
	============================================= -->
    <style>
		.slider-element { background: linear-gradient(to right, rgba(255,255,255,1) 40%, rgba(70,193,176, .7)), url('{{home.image.url}}') no-repeat 90% 100% / auto 100%; }
	  
	  @media (min-width: 992px) {
		.slider-element {
		  background: linear-gradient(to right, rgba(255,255,255,0), rgba(70,193,176, 0.17)), url('{{home.image.url}}') no-repeat 90% 100% / auto 100%;
		}
	  }
	  </style>



		<!-- Slider / Hero
		============================================= -->
		<div id="slider" class="slider-element dark py-5" >

			<!-- <div class="container">
				<div class="row">
					<div class="col-lg-5 py-5">
						<h2 class="display-4 color font-weight-normal font-display">{{home.herocontent}}</h2>
						<p class="color">{{home.subherocontent}}</p>
						
					</div>
				</div>
			</div> -->

			<div class="container">
				<div class="row text-center py-5 min-vh-md-75 ">
					<div class="col-lg-5 py-5">
						<h2 class="display-4 color font-weight-normal font-display">{{home.herocontent}}</h2>
						<p class="color" style="font-size:larger;" >{{home.subherocontent}}</p>
						
					</div>
				</div>
			</div>


		</div>

		<!-- Content
		============================================= -->
		<section id="content">
			<div class="content-wrap">

				<div class="container">

					<!-- How We Care
					============================================= -->
					<div class="row justify-content-center mt-5">
						<div class="col-md-7 text-center">
							<h3 class="display-4 color font-weight-bold font-display">{{home.pagemaintitle}}</h3>
							<p class="lead" style="line-height: 1.5">{{home.pagesubcontent}}</p>
						</div>
					</div>

					<div class="row justify-content-center align-items-center gutter-50 col-mb-80 mt-5">
						<div class="col-xl-9 col-lg-11">
							<div class="row feature-box-border col-mb-30 justify-content-center align-items-center">
								
								
								{% for homedetail in homedetails %}
								<div class="col-md-6 feature-box fbox-color fbox-border fbox-light fbox-effect">
									<div class="fbox-icon">
										<a href="#"><i>{{forloop.counter}}</i></a>
									</div>
									<div class="fbox-content">
										<h3 class="nott text-larger mb-2">{{homedetail.title}}</h3>
										<p>{{homedetail.content|safe}}</p>
									</div>
								</div>
								<div class="col-md-4 text-center">
									<img src="{{homedetail.image.url}}" alt="Image" class="p-4" height="230">
								</div>

								<div class="clear"></div>

								{% endfor %}


							</div>
						</div>
					</div>
										<!-- Section Mobile
					============================================= -->
					<div class="row justify-content-between align-items-center mt-6 col-mb-50">
						<div class="col-lg-5 order-lg-last">
							<h3 class="display-3 color font-weight-normal font-display mb-5">{{home.below_title}}</h3>

							<p class="text-large color">{{home.below_content}}</p>

							<!-- <a href="#" class="color font-weight-bold border-bottom border-width-2 border-color mr-2 text-capitalize">Learn more about our App</a><i class="icon-chevron-right icon-stacked text-smaller color"></i> -->
						</div>
						<div class="col-lg-5">
							<img src="{{home.below_image.url}}" alt="Phone call" class="rounded">
						</div>
					</div>

					<!-- Get 24/7 Care
					============================================= -->
					<div class="row justify-content-between align-items-center my-6 col-mb-50">
						<div class="col-lg-5">


							<h3 class="display-3 color font-weight-normal font-display mb-5">{{first_middle_header.title}}</h3>

							{% for middle in first_middle_header.homemiddledetail_set.all %}
							<div class="feature-box fbox-sm mb-4">
								<div class="fbox-icon">
									<i class="bg-color-50 color icon-line-calendar"></i>
								</div>
								<div class="fbox-content">
									<h3 class="nott text-larger font-weight-normal mb-2">{{middle.title}}</h3>
								</div>
							</div>
							{% endfor %}

							<!-- <a href="#" class="color font-weight-bold border-bottom border-width-2 border-color mr-2 text-capitalize">Learn more about our Support</a><i class="icon-chevron-right icon-stacked text-smaller color"></i> -->
						</div>
						<div class="col-lg-6">
							<img src="{{first_middle_header.image.url}}" alt="{{first_middle_header.image_def}}" class="rounded">
						</div>
					</div>



					<!-- Prevention of Covid-19
					============================================= -->
					<div class="row justify-content-between align-items-center my-6 col-mb-50">
						<div class="col-lg-5">
							<h3 class="display-3 color font-weight-normal font-display mb-5">{{last_middle_header.title}}</h3>

							<p class="text-large color">{{last_middle_header.content}}</p>
							{% for middle in last_middle_header.homemiddledetail_set.all %}
							<div class="feature-box fbox-sm mb-2">
								<div class="fbox-icon">
									<i class="bg-color-50 color icon-head-side-mask"></i>
								</div>
								<div class="fbox-content">
									<h3 class="nott text-larger font-weight-normal mb-2">{{middle.title}}</h3>
								</div>
							</div>
							{% endfor %}



							<div class="clear"></div>

								<!-- <a href="#" class="color font-weight-bold border-bottom border-width-2 border-color mr-2 text-capitalize">Learn more</a><i class="icon-chevron-right icon-stacked text-smaller color"></i> -->
						</div>
						<div class="col-lg-6">
							<img src="{{last_middle_header.image.url}}" alt="{{last_middle_header.image_def}}" class="rounded">
						</div>
					</div>

				</div>

				<!-- Download App Section
				============================================= -->
				<div class="section py-md-0 section-mobile bg-color-2" style="background: no-repeat center left / contain;">
					<div class="container">
						<div class="row align-items-center justify-content-between">

							<div class="col-lg-5 col-md-6 py-5 py-lg-0">
								<h3 class="display-3 color font-weight-normal font-display mb-5">{{home.last_title}}</h3>
								<p class="text-large color">{{home.last_content}}</p>
								<!-- <div>
									<a href="#"><img src="{{home.last_image1.url}}" alt="Image" height="54" class="mt-3"></a>
									<a href="#"><img src="{{home.last_image2.url}}" alt="Image"  class="ml-xl-3 ml-lg-1 mt-3 ml-0 " height="54"></a>
								</div> -->
							</div>

							<div class="col-lg-6 col-md-6 mt-5 mt-sm-0">
								<div class="d-none d-lg-flex">
									<img src="{{home.last_image1.url}}" class="fast" alt="Image" style="height: 400px" data-animate="fadeInUp" data-delay="200">
									<img src="{{home.last_image2.url}}" class="fast" alt="Image" style="height: 400px" data-animate="fadeInUp">
								</div>
								<!-- <img src="demos/covid-care/images/iphone.png" alt="Image" class="d-block d-lg-none px-5 px-sm-0 p-md-5"> -->
							</div>

						</div>
					</div>
				</div>




			</div>
		</section><!-- #content end -->

		<!-- Footer
		============================================= -->


	

	<!-- Go To Top
	============================================= -->
	<!-- <div id="gotoTop" class="icon-angle-up"></div> -->



{% endblock content %}

templates/layout.html
{% load static %} {% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="author" content="SemiColonWeb" />

    <!-- Stylesheets
	============================================= -->
    <link
      href="https://fonts.googleapis.com/css?family=Lato:300,400,400i,700|Montserrat:400,700|Crete+Round:400i&display=swap"
      rel="stylesheet"
      type="text/css"
    />
    <link
      rel="stylesheet"
      href="{% static 'css/bootstrap.css' %}"
      type="text/css"
    />
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css" />
    <link
      rel="stylesheet"
      href="{% static 'css/swiper.css' %}"
      type="text/css"
    />

    <!-- Medical Demo Specific Stylesheet -->
    <link
      rel="stylesheet"
      href="{% static 'demos/covid-care/covid-care.css' %}"
      type="text/css"
    />
    <link
      rel="stylesheet"
      href="{% static 'demos/covid-care/css/fonts.css' %}"
      type="text/css"
    />
  <!-- Favicons -->
  <link href="{{setting.favicon.url}}" rel="icon">
  <link href="{{setting.favicon.url}}" rel="apple-touch-icon">

    <link rel="stylesheet" href="{% static 'css/dark.css' %}" type="text/css" />
    <link
      rel="stylesheet"
      href="{% static 'css/font-icons.css' %}"
      type="text/css"
    />
    <!-- <link rel="stylesheet" href="{% static 'demos/medical/css/medical-icons.css' %}" type="text/css" /> -->
    <link
      rel="stylesheet"
      href="{% static 'css/animate.css' %}"
      type="text/css"
    />
    <link
      rel="stylesheet"
      href="{% static 'css/magnific-popup.css' %}"
      type="text/css"
    />

    <!-- <link rel="stylesheet" href="{% static 'demos/medical/fonts.css' %}" type="text/css" /> -->

    <link
      rel="stylesheet"
      href="{% static 'css/custom.css' %}"
      type="text/css"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
<!-- 
    <link
      rel="stylesheet"
      href="{% static 'css/colors.php?color=DE6262' %}"
      type="text/css"
    /> -->

    <!-- Document Title
	============================================= -->
  {% block title %} <title>Rasyonel Dental</title>{% endblock %}

    {% block metalar %}
    <meta content="{{setting.description}}" name="description">
    <meta content="{{setting.keywords}}" name="keywords">
    {% endblock %}
    <meta name="robots" content="all">

  </head>
  <body class="stretched">
    <div id="wrapper" class="clearfix">
      {% include "include/navbar.html" %}
      {% include 'include/messages.html' %} 


       {% block content %} 
       
       {% endblock content %} 
       
       
       {% include "include/footer.html" %}
    </div>
    <!-- #wrapper end -->
    <!-- Go To Top
	============================================= -->







  <!-- <a  href="https://api.whatsapp.com/send?phone={{setting.whatsapp_phone}}" class="back-to-left"><i class="icofont-brand-whatsapp" ></i></a> -->

    <div id="gotoTop" class="icon-angle-up rounded-circle"></div>
  

    <!-- JavaScripts
	============================================= -->
    <script src="{% static  'js/jquery.js' %}"></script>
    <script src="{% static  'js/plugins.min.js' %}"></script>
    <!-- <script src="{% static 'lozad.min.js' %}"></script> -->

    <!-- Footer Scripts
	============================================= -->
    <script src="{% static  'js/functions.js' %}"></script>
    <!-- <script>
      const observer = lozad();
      observer.observe();
    </script> -->
  </body>
</html>